WITH CURR_BASE AS ( SELECT  SGBSTDN_PIDM PIDM,
                            ENRL_TERM.SFRSTCR_TERM_CODE REG_TERM,
                            MAX(SGBSTDN_TERM_CODE_EFF) CURR_BASE     --return every unique pidm/term combo from SFRSTCR, then find max SGBSTDN record for that student pidm in that term
                    FROM BANNER.SATURN.SGBSTDN BASE
                    INNER JOIN (SELECT DISTINCT SFRSTCR_PIDM, SFRSTCR_TERM_CODE
                                FROM BANNER.SATURN.SFRSTCR
                                WHERE SFRSTCR_RSTS_CODE IN (    SELECT STVRSTS_CODE
                                                                FROM BANNER.SATURN.STVRSTS
                                                                WHERE STVRSTS_INCL_SECT_ENRL = 'Y')
                                    AND SFRSTCR_PTRM_CODE != 'H') ENRL_TERM ON ENRL_TERM.SFRSTCR_PIDM = BASE.SGBSTDN_PIDM
                    WHERE BASE.SGBSTDN_TERM_CODE_EFF <= ENRL_TERM.SFRSTCR_TERM_CODE
                    GROUP BY SGBSTDN_PIDM, ENRL_TERM.SFRSTCR_TERM_CODE)
SELECT CB.PIDM, CB.REG_TERM, STVTERM_DESC, STVMAJR_DESC
FROM CURR_BASE CB
LEFT OUTER JOIN BANNER.SATURN.SGBSTDN S ON S.SGBSTDN_PIDM = CB.PIDM AND S.SGBSTDN_TERM_CODE_EFF = CB.CURR_BASE
LEFT OUTER JOIN BANNER.SATURN.STVMAJR ON STVMAJR_CODE = S.SGBSTDN_MAJR_CODE_1
LEFT OUTER JOIN BANNER.SATURN.STVTERM ON STVTERM_CODE = CB.REG_TERM
WHERE S.SGBSTDN_LEVL_CODE='UG'
    AND S.SGBSTDN_COLL_CODE_1='14'
    AND REG_TERM LIKE '%70'
    AND REG_TERM>='201870'